version: 0.0
os: linux
files:
  - source: /
    destination: /home/bitnami/stack/build
file_exists_behavior: OVERWRITE
hooks:
   AfterInstall:
    - location: scripts/npm_install.sh
      timeout: 300
      runas: root
   ApplicationStart:
    - location: scripts/npm_build.sh
      timeout: 300
      runas: root

 
